### ISSUE TITLE
Calendar Headers color issue

### ISSUE THREAD

**Issue by slodziak** [tgcowell/waves#6] opened 2021-08-20 13:12 UTC
Really nice theme, appreciate the hard work! However, it seems that the dark mode version suffers when the HA native calendar card is present. The header part shows in light color instead of following the rest of the theme.

![calendar](https://user-images.githubusercontent.com/16757515/130238394-1a69357a-2964-47c4-ab01-5d91605e7ffe.png)

Thank you!

**Comment by tgcowell** [comment] 2021-08-21 00:57
Hi @slodziak,

Thanks for the heads up, will try and work out what it's using and provide an update shortly.

Thanks 🙏

**Comment by tgcowell** [comment] 2021-08-25 06:14
Hi @slodziak,

I've been slowly chipping away at this issue and here is what I have found so far.

- If you remove the background the bars will then reflect what the actual css or yaml file. Which is var(--ha-card-background) so in theory it should all blend in as you have clearly suggested.
- I've tested this with other

**Comment by tgcowell** [comment] 2021-08-25 06:31
I have found the issue... just not sure why it's happening. The var(--ha-card-background) is rgba set at .15 opacity so they are see through. If I make it 1 so it's not clear the issue is resolve. So for some reason it doesn't like that. At least it's a step in the right direction.

**Comment by tgcowell** [comment] 2021-08-25 06:45
Hi @slodziak 

I've made a minor change that helps remove the contrasting 'white' table row and moves it into a more dull grey. It's got something to do with the actual -fc-neutral-bg-color but despite several attempts to change this the core theme would always override my variables.

While it's not what I was hoping to do, it's the best I can provide for now. I'm going to close it as I believe it's an improvement, however please note I'll see what I can do moving forward.

Thanks again

**Closed by tgcowell** 2021-08-25 06:45 UTC
Labels: bug
